version: '3.8'

services:
  postgres-second:
    image: postgres:15
    container_name: postgres-second
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: second_db
    ports:
      - "5433:5432" 
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata2:

networks:
  backend:
